### ISSUE TITLE
Grade Comments

### ISSUE THREAD

**Issue by aclavin-eab** [thenuttyirishman/Word-Guess-Game#1]
Looks great; some inconsistencies in the indentation in javascript that can really trip you up where you are and what scope you're in. Very important to be careful of that. Would also like to see some comments in the javascript to describe your intention and thought process. Great job this week, keep it up!

**Comment by aclavin-eab** [comment]
Oh also shouldn't start in a failed game state, where if you press a key it tells you, you lose, maybe priming the game by running the restart game function

**Comment by thenuttyirishman** [comment]
Thank you Andrew!
